language: ruby

install:
  - gem install jekyll html-proofer

script:
  - jekyll build --verbose --safe
  - >
    htmlproofer
    --check-favicon
    --check-html
    --check-img-http
    --enforce-https
    --log-level=debug
    --only-4xx
    --report-eof-tags
    --report-invalid-tags
    --report-mismatched-tags
    --report-missing-doctype
    --report-missing-names
    --report-script-embeds
    _site/
